### ISSUE TITLE
H3_SETTINGS_ERROR for duplicate settings identifiers

### ISSUE THREAD

**Issue by dtikhonov** [kazu-yamamoto/h3spec#2]
`h3spec` says that

> HTTP/3 servers/MUST send H3_SETTINGS_ERROR if duplicate setting identifiers exist [HTTP/3 7.2.4]

Which is incorrect, as the [HTTP I-D states](https://tools.ietf.org/html/draft-ietf-quic-http-34#section-7.2.4):

```
   The same setting identifier MUST NOT occur more than once in the
   SETTINGS frame.  A receiver MAY treat the presence of duplicate
   setting identifiers as a connection error of type H3_SETTINGS_ERROR.
```

**Comment by kazu-yamamoto** [comment]
Oh, this is MAY. I will fix it. Thanks.

**Comment by kazu-yamamoto** [comment]
It appeared that I made a mistake that disabled 7.2.4.1 in 8d9e2dc7bad8621fb9b2c529a7394408dd88ac70.
5f21d091a0f83a876265ea89e7e14533f86a7f1a enables 7.2.4.1 (MUST) again and disables 7.2.4 (MAY).

**Comment by kazu-yamamoto** [comment]
A new version has been released. Thank you for your report.
